# Generated by Django 5.0.2 on 2024-02-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcat',
            name='product_image',
            field=models.FileField(default='', upload_to='product_picture'),
        ),
    ]
